# Rutas que incluye por defecto la distribución estándar
_welcome:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo


# Rutas del proyecto Desymfony
_ponencias:
    resource: @PonenciaBundle/Resources/config/routing.yml

_admin_ponencias:
    resource: @PonenciaBundle/Resources/config/admin_routing.yml
    prefix:   /admin/ponencia

_ponentes:
    resource: @PonenteBundle/Resources/config/routing.yml

_usuarios:
    resource: @UsuarioBundle/Resources/config/routing.yml

_comun:
    resource: @ComunBundle/Resources/config/routing.yml
