# Rutas del proyecto Desymfony
_ponencias:
    resource: @DesymfonyBundle/Resources/config/ponencia_routing.yml

_ponentes:
    resource: @DesymfonyBundle/Resources/config/ponente_routing.yml

_comun:
    resource: @DesymfonyBundle/Resources/config/routing.yml
