security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path:  /login
                check_path:  /perfil/check
            logout:
                path:   /perfil/logoff
                target: /
                
    access_control:
        - { path: ^/perfil, roles: ROLE_USER }

    providers:
#        in_memory:
#            users:
#                ryan:  { password: ryanpass, roles: 'ROLE_USER' }
#                admin: { password: kitten, roles: 'ROLE_ADMIN' }
        main:
            entity: { class: Desymfony\DesymfonyBundle\Entity\Usuario, property: email }

    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
        Desymfony\DesymfonyBundle\Entity\Usuario: plaintext
