security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path:  /login
                check_path:  /check
            logout:
                path:   /logout
                target: /
    
    access_denied_url: /denegado
    
    access_control:
        - { path: ^/perfil        , roles: ROLE_USER }
        - { path: ^/me-apunto-a-* , roles: ROLE_USER }
        - { path: ^/registro      , roles: IS_AUTHENTICATED_ANONYMOUSLY }

    providers:
        main:
            providers: [user_db]
        user_db:
            entity: { class: Desymfony\DesymfonyBundle\Entity\Usuario, property: email }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Desymfony\DesymfonyBundle\Entity\Usuario:  sha512
